### ISSUE TITLE
Wrong Manchester Encoded Capture

### ISSUE THREAD

**Issue by m4l490n** [tresacton/dspectrumgui#14]
### Expected Behaviour
The capture is being shown all ones and zeroes inverted for a 128 bit manchester encoded capture. The capture is:
`11101001010111001110000101100011111110100110110000010111000111101111111111111111010011011000101011111111111111110110111000111001`

`(HEX: \xe9\x5c\xe1\x63\xfa\x6c\x17\x1e\xff\xff\x4d\x8a\xff\xff\x6e\x39)`

Which had it been inverted, it will be correct. Then DSPectrumGUI is telling that the capture is not a valid manchester encoding value on neither of the two **G. E. Thomas** or **IEEE 802** Format formats.

### Actual Behaviour
The value should be:

`00010110101000110001111010011100000001011001001111101000111000010000000000000000101100100111010100000000000000001001000111000110`

`(HEX: \x16\xA3\x1E\x9C\x05\x93\xE8\xE1\xB2\x75\x00\x00\x91\xC6)`

I include an image of inspectrum for the capture with an overlay of the correct decodification made by hand.

![image](https://user-images.githubusercontent.com/22749875/41169955-8950d844-6b18-11e8-8371-4433a1e3cf64.png)

### What commit were you running? 
You are currently running: v0.1.1-beta-34-gbd0d2c2 || bd0d2c25be5b41fd5e3bd3b0ad0366ba5f9f3d20
This app is up-to-date with master

**Comment by tresacton** [comment]
taking a look at your second issue, the raw binary: 
`00010110101000110001111010011100000001011001001111101000111000010000000000000000101100100111010100000000000000001001000111000110
`
converts to: 
`16 A3 1E 9C 05 93 E8 E1 00 00 B2 75 00 00 91 C6`

I believe this issue is user error, but I'm happy to help you work through and find where you went wrong if you require. Please take another look at the PDF guide for hints as to how correctly aligned grids and pulses should appear, and another look at how you decoded the binary to hex. I performed the example above programatically (in a terminal session) and also in a binary to hex conversion website, with identical results.
